[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"

[font]
size = 15.0

[font.bold]
family = "menlo"
style = "Bold"

[font.bold_italic]
family = "menlo"
style = "Italic"

[font.italic]
family = "menlo"
style = "Italic"

[font.normal]
family = "menlo"
style = "Regular"
[window]
opacity = 1.0
[cursor.style]
shape = "Underline"
blinking = "Always"

