[colors.bright]
black = "0x2e3436"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeeec"
yellow = "0xfce94f"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x73d216"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xedd400"

[colors.primary]
foreground = "0xeeeeec"

[font]
size = 12

[font.bold]
family = "jetbrains mono"
style = "Bold"

[font.italic]
family = "jetbrains mono"
style = "Italic"

[font.normal]
family = "jetbrains mono"
style = "Regular"

[window]
opacity = 0.7
